'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import { FileText, Search, Download, CalendarDays, ExternalLink } from 'lucide-react';
import { format, parseISO } from 'date-fns';

interface Report {
    id: string;
    eventId: string;
    status: string;
    reportFileUrl: string | null;
    createdAt: string;
    event: {
        id: string;
        title: string;
        category: string;
        startTime: string;
        endTime: string;
        hall: { name: string } | null;
    };
    createdBy: {
        id: string;
        name: string;
    };
}

export default function ReportsPage() {
    const [reports, setReports] = useState<Report[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const res = await api.get('/reports');
                setReports(res.data);
            } catch (err) {
                console.error("Failed to load reports", err);
            } finally {
                setLoading(false);
            }
        };
        fetchReports();
    }, []);

    const filtered = reports.filter(r => 
        r.event?.title.toLowerCase().includes(search.toLowerCase()) ||
        r.createdBy?.name.toLowerCase().includes(search.toLowerCase())
    );

    return (
        <div className="flex flex-col gap-6" style={{ paddingBottom: '4rem' }}>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight mb-1">Event Reports</h1>
                    <p className="text-muted-foreground text-sm">View and download AI-generated post-event completion reports.</p>
                </div>
                <div className="flex items-center gap-2 w-full max-w-sm relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                    <input 
                        className="flex h-10 w-full rounded-md border border-input bg-background pl-9 px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2" 
                        placeholder="Search by event or host..."
                        value={search} onChange={e => setSearch(e.target.value)}
                    />
                </div>
            </div>

            <div className="border rounded-xl bg-card shadow-sm overflow-hidden">
                {loading ? (
                    <div className="p-12 text-center text-muted-foreground flex flex-col items-center">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mb-4"></div>
                        <p>Loading reports...</p>
                    </div>
                ) : filtered.length === 0 ? (
                    <div className="flex flex-col items-center justify-center p-16 text-center">
                        <div className="bg-secondary p-4 rounded-full mb-4">
                            <FileText size={32} className="text-muted-foreground" />
                        </div>
                        <h3 className="text-lg font-semibold mb-2">No reports found</h3>
                        <p className="text-muted-foreground text-sm max-w-md">There are currently no AI-generated post-event reports available matching your criteria.</p>
                    </div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-secondary/50 text-muted-foreground uppercase text-xs font-semibold">
                                <tr>
                                    <th className="px-6 py-4">Event Details</th>
                                    <th className="px-6 py-4">Generated By</th>
                                    <th className="px-6 py-4">Status</th>
                                    <th className="px-6 py-4">Date Generated</th>
                                    <th className="px-6 py-4 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y text-foreground">
                                {filtered.map((report) => (
                                    <tr key={report.id} className="hover:bg-accent/20 transition-colors">
                                        <td className="px-6 py-4">
                                            <div className="font-semibold">{report.event?.title || 'Unknown Event'}</div>
                                            <div className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                                                <CalendarDays size={12} />
                                                {report.event?.startTime ? format(parseISO(report.event.startTime), 'MMM d, yyyy') : 'N/A'}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="font-medium">{report.createdBy?.name || 'Unknown'}</div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={\`text-[0.65rem] px-2.5 py-1 rounded-full font-bold \${report.status === 'GENERATED' ? 'bg-lime-500/10 text-lime-600' : report.status === 'DRAFT' ? 'bg-amber-500/10 text-amber-600' : 'bg-red-500/10 text-red-600'}\`}>
                                                {report.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground">
                                            {format(parseISO(report.createdAt), 'MMM d, yyyy • h:mm a')}
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            {report.status === 'GENERATED' && report.reportFileUrl ? (
                                                <a href={report.reportFileUrl} target="_blank" rel="noopener noreferrer" className="btn btn-primary btn-sm inline-flex items-center gap-1.5 focus:scale-95 transition-transform">
                                                    <Download size={14} /> Download DOCX
                                                </a>
                                            ) : (
                                                <button disabled className="btn btn-secondary btn-sm opacity-50 cursor-not-allowed inline-flex items-center gap-1.5">
                                                    <ExternalLink size={14} /> Processing
                                                </button>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
}
