'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import { FileText, Search, Download, CalendarDays, ExternalLink } from 'lucide-react';
import { format, parseISO } from 'date-fns';

interface Report {
    id: string;
    eventId: string;
    status: string;
    reportFileUrl: string | null;
    createdAt: string;
    event: {
        id: string;
        title: string;
        category: string;
        startTime: string;
        endTime: string;
        hall: { name: string } | null;
    };
    createdBy: {
        id: string;
        name: string;
    };
}

export default function ReportsPage() {
    const [reports, setReports] = useState<Report[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const res = await api.get('/reports');
                setReports(res.data);
            } catch (err) {
                console.error("Failed to load reports", err);
            } finally {
                setLoading(false);
            }
        };
        fetchReports();
    }, []);

    const filtered = reports.filter(r => 
        r.event?.title.toLowerCase().includes(search.toLowerCase()) ||
        r.createdBy?.name.toLowerCase().includes(search.toLowerCase())
    );

    return (
        <div className="flex flex-col gap-6" style={{ paddingBottom: '4rem' }}>
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                <div>
                    <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-1 bg-gradient-to-br from-foreground to-foreground/60 bg-clip-text text-transparent pb-1">Event Reports</h1>
                    <p className="text-muted-foreground text-base max-w-lg">View and download AI-generated post-event completion reports.</p>
                </div>
                <div className="flex items-center gap-2 w-full max-w-sm relative group">
                    <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground transition-colors group-focus-within:text-primary" />
                    <input 
                        className="flex h-11 w-full rounded-full border border-input bg-secondary/30 pl-10 pr-4 py-2 text-sm ring-offset-background placeholder:text-muted-foreground hover:border-white/20 transition-all focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary/50 focus-visible:border-primary shadow-sm" 
                        placeholder="Search by event or host..."
                        value={search} onChange={e => setSearch(e.target.value)}
                    />
                </div>
            </div>

            <div className="bento-item p-0 overflow-hidden relative">
                {loading ? (
                    <div className="p-16 text-center text-muted-foreground flex flex-col items-center">
                        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mb-4"></div>
                        <p>Loading reports...</p>
                    </div>
                ) : filtered.length === 0 ? (
                    <div className="flex flex-col items-center justify-center p-20 text-center relative overflow-hidden">
                        <div className="absolute inset-0 bg-secondary/5 pointer-events-none"></div>
                        <div className="bg-gradient-to-br from-indigo-500/10 to-purple-500/10 p-5 rounded-full mb-5 border border-indigo-500/20">
                            <FileText size={36} className="text-indigo-400" />
                        </div>
                        <h3 className="text-xl font-bold mb-2 text-foreground">No reports found</h3>
                        <p className="text-muted-foreground max-w-md leading-relaxed">We couldn't find any reports matching your search. Try adjusting your filters or generate a new report from an event page.</p>
                    </div>
                ) : (
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm text-left">
                            <thead className="bg-white/5 backdrop-blur-sm text-white/70 uppercase text-xs font-bold tracking-wider border-b border-white/10">
                                <tr>
                                    <th className="px-6 py-5">Event Details</th>
                                    <th className="px-6 py-5">Generated By</th>
                                    <th className="px-6 py-5">Status</th>
                                    <th className="px-6 py-5">Date Generated</th>
                                    <th className="px-6 py-5 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y text-foreground">
                                {filtered.map((report) => (
                                    <tr key={report.id} className="hover:bg-accent/20 transition-colors">
                                        <td className="px-6 py-4">
                                            <div className="font-semibold">{report.event?.title || 'Unknown Event'}</div>
                                            <div className="text-xs text-muted-foreground flex items-center gap-1 mt-1">
                                                <CalendarDays size={12} />
                                                {report.event?.startTime ? format(parseISO(report.event.startTime), 'MMM d, yyyy') : 'N/A'}
                                            </div>
                                        </td>
                                        <td className="px-6 py-4">
                                            <div className="font-medium">{report.createdBy?.name || 'Unknown'}</div>
                                        </td>
                                        <td className="px-6 py-5">
                                            <span className={`text-[0.65rem] px-3 py-1.5 rounded-full font-bold uppercase tracking-widest ${report.status === 'GENERATED' ? 'bg-lime-500/10 text-lime-400 border border-lime-500/20' : report.status === 'DRAFT' ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20' : 'bg-red-500/10 text-red-400 border border-red-500/20'}`}>
                                                {report.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground">
                                            {format(parseISO(report.createdAt), 'MMM d, yyyy • h:mm a')}
                                        </td>
                                        <td className="px-6 py-5 text-right">
                                            {report.status === 'GENERATED' && report.reportFileUrl ? (
                                                <a href={report.reportFileUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center justify-center gap-2 h-9 px-4 rounded-full bg-indigo-600 hover:bg-indigo-700 text-white shadow-[0_0_15px_rgba(99,102,241,0.3)] transition-all hover:-translate-y-0.5 text-xs font-bold">
                                                    <Download size={14} /> Download DOCX
                                                </a>
                                            ) : (
                                                <button disabled className="inline-flex items-center justify-center gap-2 h-9 px-4 rounded-full bg-white/5 text-white/50 border border-white/10 cursor-not-allowed text-xs font-bold">
                                                    <ExternalLink size={14} /> Processing
                                                </button>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
}
