const express = require('express');
const { v4: uuidv4 } = require('uuid');
const supabase = require('../lib/supabase');
const { authenticate, requireAdmin } = require('../middleware/auth.middleware');
const { auditLog } = require('../lib/audit');

const router = express.Router();

const {
    Document, Packer, Paragraph, TextRun,
    AlignmentType, BorderStyle, UnderlineType
} = require('docx');

// ─── OpenRouter config ───
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
const OPENROUTER_MODEL = 'anthropic/claude-3.7-sonnet';

// ─── POST /api/reports/:eventId — Submit questionnaire + generate IEEE report ───
router.post('/:eventId', authenticate, requireAdmin, async (req, res) => {
    const { responses } = req.body;
    if (!responses) return res.status(400).json({ error: 'Responses are required.' });

    const { data: event } = await supabase.from('Event')
        .select('id, title, description, startTime, endTime, category, expectedAttendance, createdBy, hall:Hall(name, location), creator:User(name, email), organization:Organization(name)')
        .eq('id', req.params.eventId).single();

    if (!event) return res.status(404).json({ error: 'Event not found.' });
    if (event.createdBy !== req.user.id && req.user.role !== 'SUPER_ADMIN') {
        return res.status(403).json({ error: 'Only the event creator can create a report.' });
    }

    const { data: existingReport } = await supabase.from('EventReport')
        .select('id, status').eq('eventId', req.params.eventId).single();
    if (existingReport) {
        if (existingReport.status === 'GENERATED' && existingReport.reportFileUrl) {
            return res.status(409).json({
                error: 'A report already exists for this event.',
                report: existingReport
            });
        }
        // If it's DRAFT or FAILED, delete it and start fresh
        await supabase.from('EventReport').delete().eq('id', existingReport.id);
    }

    const reportId = uuidv4();
    const { error: insertErr } = await supabase.from('EventReport').insert({
        id: reportId,
        eventId: req.params.eventId,
        createdById: req.user.id,
        responses: JSON.stringify(responses),
        status: 'DRAFT',
        createdAt: new Date().toISOString(),
    });
    if (insertErr) return res.status(500).json({ error: insertErr.message });

    try {
        const prompt = buildReportPrompt(event, responses);

        const aiResponse = await fetch('https://openrouter.ai/api/v1/chat/completions', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
                'Content-Type': 'application/json',
                'HTTP-Referer': 'https://campusflow.app',
                'X-Title': 'CampusFlow Event Reports',
            },
            body: JSON.stringify({
                model: OPENROUTER_MODEL,
                messages: [
                    {
                        role: 'system',
                        content: `You write post-event reports in IEEE standard documentation format for academic and student organizations. Your reports are formal but read like they were written by a careful human, not generated by an algorithm.

WRITING RULES (follow all of them):
- No inflated language: avoid "pivotal", "vibrant", "groundbreaking", "testament to", "showcasing", "underscoring", "delve", "tapestry", "landscape" (abstract use), "interplay"
- No promotional tone: state facts plainly
- No stacked -ing phrases: not "highlighting X, contributing to Y, ensuring Z"
- No vague attributions: not "experts believe", "observers noted" — state specifics
- No generic endings: not "the future looks bright" or "exciting times lie ahead"
- No em-dash overuse, no emoji, no bolded headers inside section text
- Use simple copulas: "is", "are", "has" instead of "serves as", "stands as", "boasts"
- Vary sentence length naturally — mix short and longer sentences
- Be specific: use numbers, names, places, durations wherever available
- Maintain formal register without sounding assembled or hollow

OUTPUT FORMAT: Return ONLY valid JSON with exactly these 11 keys. Each value is one or two plain-text paragraphs (no bullet points, no markdown inside):

{
  "abstract": "...",
  "introduction": "...",
  "eventObjectives": "...",
  "programOverview": "...",
  "attendanceAndParticipation": "...",
  "outcomesAndAchievements": "...",
  "challengesAndResolutions": "...",
  "financialOverview": "...",
  "feedbackAndAnalysis": "...",
  "conclusionsAndRecommendations": "...",
  "acknowledgements": "..."
}

No code blocks. No extra text. Raw JSON only.`
                    },
                    { role: 'user', content: prompt },
                ],
                max_tokens: 6000,
                temperature: 0.35,
                response_format: { type: 'json_object' }
            }),
        });

        const aiData = await aiResponse.json();
        const aiText = aiData.choices?.[0]?.message?.content;
        let reportJson = {};
        try {
            reportJson = JSON.parse(aiText);
        } catch (e) {
            console.error('[Report] AI returned invalid JSON:', aiText);
            throw new Error('Failed to parse AI response as JSON');
        }

        // ─── Build IEEE-standard Word Document ───
        const reportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
        const eventDateStr = new Date(event.startTime).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
        const eventTimeStr = `${new Date(event.startTime).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} to ${new Date(event.endTime).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`;
        const orgName = event.organization?.name || 'CampusFlow';
        const refCode = `CF-RPT-${reportId.slice(0, 8).toUpperCase()}`;

        // Helpers
        const TNR = (text, opts = {}) => new TextRun({ text, font: 'Times New Roman', size: 24, ...opts });

        const centeredPara = (runs, spacingBefore = 0, spacingAfter = 120) => new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: spacingBefore, after: spacingAfter },
            children: Array.isArray(runs) ? runs : [runs],
        });

        const metaRow = (label, value) => new Paragraph({
            spacing: { after: 60 },
            children: [
                TNR(`${label}: `, { bold: true, size: 22 }),
                TNR(value || 'N/A', { size: 22 }),
            ]
        });

        const sectionHeading = (num, title) => new Paragraph({
            spacing: { before: 400, after: 140 },
            children: [TNR(`${num}.  ${title.toUpperCase()}`, { bold: true, size: 24 })]
        });

        const bodyPara = (text) => new Paragraph({
            alignment: AlignmentType.JUSTIFIED,
            spacing: { after: 200, line: 360 },
            children: [TNR(text || 'Not provided.', { size: 22 })]
        });

        const hrule = () => new Paragraph({
            spacing: { before: 160, after: 160 },
            border: { bottom: { color: '333333', space: 1, style: BorderStyle.SINGLE, size: 4 } },
            children: []
        });

        const children = [];

        // ── Cover block ──
        children.push(centeredPara(TNR(orgName.toUpperCase(), { bold: true, size: 26, allCaps: true }), 480, 80));
        children.push(centeredPara(TNR('POST-EVENT TECHNICAL REPORT', { bold: true, size: 34 }), 0, 80));
        children.push(centeredPara(TNR(event.title, { bold: true, size: 28, italics: true }), 0, 80));
        children.push(hrule());

        // ── Document metadata table ──
        children.push(metaRow('Report Reference No.', refCode));
        children.push(metaRow('Category', event.category));
        children.push(metaRow('Event Date', eventDateStr));
        children.push(metaRow('Time', eventTimeStr));
        children.push(metaRow('Venue', `${event.hall?.name || 'N/A'} — ${event.hall?.location || 'N/A'}`));
        children.push(metaRow('Organizing Body', orgName));
        children.push(metaRow('Prepared by', event.creator?.name || 'N/A'));
        children.push(metaRow('Report Date', reportDate));
        children.push(metaRow('Expected Attendance', String(event.expectedAttendance)));
        children.push(metaRow('Actual Attendance', String(responses.actualAttendance || 'N/A')));
        children.push(hrule());

        // ── Abstract ──
        children.push(centeredPara(TNR('ABSTRACT', { bold: true, size: 26 }), 240, 100));
        children.push(bodyPara(reportJson.abstract));
        children.push(hrule());

        // ── Numbered Sections ──
        const sections = [
            [1, 'Introduction',                   reportJson.introduction],
            [2, 'Event Objectives',               reportJson.eventObjectives],
            [3, 'Program Overview',               reportJson.programOverview],
            [4, 'Attendance and Participation',   reportJson.attendanceAndParticipation],
            [5, 'Outcomes and Achievements',      reportJson.outcomesAndAchievements],
            [6, 'Challenges and Resolutions',     reportJson.challengesAndResolutions],
            [7, 'Financial Overview',             reportJson.financialOverview],
            [8, 'Feedback and Analysis',          reportJson.feedbackAndAnalysis],
            [9, 'Conclusions and Recommendations',reportJson.conclusionsAndRecommendations],
            [10,'Acknowledgements',               reportJson.acknowledgements],
        ];

        for (const [num, title, content] of sections) {
            children.push(sectionHeading(num, title));
            children.push(bodyPara(content));
        }

        // ── Footer ──
        children.push(hrule());
        children.push(centeredPara(
            TNR(`End of Report  |  ${refCode}  |  Generated by CampusFlow  |  ${reportDate}`, { size: 18, italics: true, color: '777777' }),
            120, 0
        ));

        // ── Assemble document ──
        const doc = new Document({
            styles: {
                default: {
                    document: {
                        run: { font: 'Times New Roman', size: 22 },
                        paragraph: { spacing: { line: 360 } }
                    }
                }
            },
            sections: [{
                properties: {
                    page: {
                        margin: { top: 1440, bottom: 1440, left: 1800, right: 1440 } // 1.25" left, 1" others (IEEE style)
                    }
                },
                children
            }]
        });

        const buffer = await Packer.toBuffer(doc);

        // ── Upload to Supabase Storage ──
        const fileName = `report_${reportId}.docx`;
        const { error: uploadErr } = await supabase.storage
            .from('event-images')
            .upload(fileName, buffer, {
                contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                upsert: false
            });

        let reportFileUrl = null;
        if (!uploadErr) {
            const { data: urlData } = supabase.storage.from('event-images').getPublicUrl(fileName);
            reportFileUrl = urlData.publicUrl;
        } else {
            console.warn('[Report] Upload warning:', uploadErr.message);
        }

        await supabase.from('EventReport')
            .update({ status: 'GENERATED', reportFileUrl })
            .eq('id', reportId);

        await auditLog(req.user.id, 'REPORT_CREATED', reportId, { eventId: req.params.eventId });

        res.status(201).json({
            id: reportId,
            eventId: req.params.eventId,
            status: 'GENERATED',
            reportFileUrl,
            reportContent: JSON.stringify(reportJson),
        });

    } catch (aiError) {
        console.error('[AI Report Error]', aiError);
        await supabase.from('EventReport').update({ status: 'ERROR' }).eq('id', reportId);
        res.status(500).json({ error: 'AI report generation failed. The draft has been saved.' });
    }
});

// ─── GET /api/reports/:eventId — Fetch event report ───
router.get('/:eventId', authenticate, async (req, res) => {
    const { data: report } = await supabase.from('EventReport')
        .select('id, eventId, responses, reportFileUrl, status, createdAt, createdBy:User(id, name, email)')
        .eq('eventId', req.params.eventId).single();
    if (!report) return res.status(404).json({ error: 'No report found for this event.' });
    res.json(report);
});

// ─── GET /api/reports — List all reports ───
router.get('/', authenticate, requireAdmin, async (req, res) => {
    const { category, search, from, to } = req.query;
    let query = supabase.from('EventReport')
        .select('id, eventId, status, reportFileUrl, createdAt, event:Event(id, title, category, startTime, endTime, organizationId, hall:Hall(name)), createdBy:User(id, name)')
        .order('createdAt', { ascending: false });
    const { data: reports, error } = await query;
    if (error) return res.status(500).json({ error: error.message });
    let filtered = reports || [];
    if (category) filtered = filtered.filter(r => r.event?.category === category);
    if (search) filtered = filtered.filter(r => r.event?.title?.toLowerCase().includes(search.toLowerCase()));
    if (from) filtered = filtered.filter(r => new Date(r.event?.startTime) >= new Date(from));
    if (to) filtered = filtered.filter(r => new Date(r.event?.startTime) <= new Date(to));
    res.json(filtered);
});

// ─── Helper: Prompt builder ───
function buildReportPrompt(event, responses) {
    return `Write a post-event report for the following campus event. Use formal language that reads like a careful human wrote it. Be specific. Use numbers where available. Avoid vague claims.

EVENT DETAILS
- Title: ${event.title}
- Category: ${event.category}
- Description: ${event.description}
- Venue: ${event.hall?.name || 'N/A'}, ${event.hall?.location || 'N/A'}
- Date and Time: ${new Date(event.startTime).toLocaleString()} to ${new Date(event.endTime).toLocaleString()}
- Expected Attendance: ${event.expectedAttendance}
- Organizing Body: ${event.organization?.name || 'N/A'}
- Report Prepared By: ${event.creator?.name || 'N/A'}

HOST RESPONSES (post-event questionnaire)
1. Actual Attendance: ${responses.actualAttendance || 'Not provided'}
2. Highlights of the Event: ${responses.highlights || 'Not provided'}
3. Challenges Faced: ${responses.challenges || 'Not provided'}
4. Budget and Sponsorship: ${responses.budget || 'Not provided'}
5. Key Takeaways: ${responses.takeaways || 'Not provided'}
6. Participant Feedback: ${responses.feedbackSummary || 'Not provided'}
7. Suggestions for Next Time: ${responses.suggestions || 'Not provided'}
8. Additional Notes: ${responses.additionalNotes || 'Not provided'}

Generate all 11 sections now. Each section: one or two formal plain-text paragraphs. No bullet points. No markdown. Specific over vague.`;
}

module.exports = router;
