/**
 * Application-wide constants for CampusFlow.
 */

const ROLES = { ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' };

const EVENT_STATUS = {
  CONFIRMED: 'CONFIRMED',
  PENDING: 'PENDING',
  CANCELLED: 'CANCELLED',
  CONFLICT_REQUESTED: 'CONFLICT_REQUESTED',
};

const INVITE_TYPE = { PUBLIC: 'PUBLIC', INVITE_ONLY: 'INVITE_ONLY' };

const REQUEST_STATUS = { PENDING: 'PENDING', APPROVED: 'APPROVED', REJECTED: 'REJECTED' };

const RECURRENCE_TYPE = { WEEKLY: 'WEEKLY', MONTHLY: 'MONTHLY', CUSTOM: 'CUSTOM' };

module.exports = { ROLES, EVENT_STATUS, INVITE_TYPE, REQUEST_STATUS, RECURRENCE_TYPE };


// Usage: const { ROLES, EVENT_STATUS } = require("../lib/constants");
